import React from "react";

// TODO: See what image/representation of ERD we can pass
interface ExportRendererProps {
  erd: unknown;
}

const ExportRenderer = React.forwardRef<HTMLDivElement, ExportRendererProps>(({ erd }, ref) => {
  if (!erd) {
    return null;
  }

  return (
  // intentionally fixed width since we render a png of it
    <div style={{ backgroundColor: "#efefef", color: "#313131" }} className="flex flex-col items-center p-16 w-[64rem]" ref={ref}>

      {/* TODO: I dont think a header should be added here */}
      {/* <h2 className="text-3xl font-semibold mb-3.5">View <span className="bg-blue-100 text-blue-800 px-2 py-1 rounded">{view.view.name}</span></h2> */}
      <div className="font-mono text-xl w-full bg-slate-200 border-2 max-w-4xl min-h-40 border-none my-">
        {/* erd here */}
      </div>

      <p className="text-xl font-semibold p-2">Generated by SQL Validator at {new Date().toISOString()}</p>
    </div>
  );
});

ExportRenderer.displayName = "ExportRenderer";

export default ExportRenderer;
